// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxvymoxmhgwdkylxwwuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dnltb3htaGd3ZGt5bHh3d3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjUwOTEsImV4cCI6MjA2NjUwMTA5MX0.jhRdLG8BL67BOgaCKj_n8B1xsxRoQAP4dUlrdKCbW38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);